---
version: "3.8"

services:
  kna-historie:
    image: ghcr.io/mark-me/kna-history:latest
    container_name: kna-historie
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - FLASK_SECRET=${FLASK_SECRET}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - resources:/data/resources
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - internal_network
      - public_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  mariadb:
    image: mariadb:10.11.6
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --bind-address=0.0.0.0
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - TZ=Europe/Amsterdam
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - PUID=1000
      - PGID=1000
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    depends_on:
      kna-historie:
        condition: service_healthy
    networks:
      - internal_network
      - public_network

  certbot-auto:
    container_name: certbot
    build:
      context: ./certbot-auto
    restart: unless-stopped
    volumes:
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
    networks:
      - internal_network
      - public_network

  duckdns:
    image: ghcr.io/linuxserver/duckdns:version-369fbd5c
    container_name: duckdns
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SUBDOMAINS=${DUCKDNS_SUBDOMAIN}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false
    networks:
      - internal_network
      - public_network

networks:
  internal_network:
    driver: bridge
  public_network:
    driver: bridge

volumes:
  resources:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_RESOURCES}
      o: "bind,rw"
  db:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_MARIADB}
      o: "bind,rw"
